### ISSUE TITLE
Drawbot 3.64 Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [loicsander/Font2PDF#2]
Traceback (most recent call last):
  File "DB-compare-glyphs.py", line 28, in <module>
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/robofab/objects/objectsRF.py", line 38, in OpenFont
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/robofab/objects/objectsRF.py", line 119, in **init**
  File "posixpath.pyc", line 360, in abspath
  File "posixpath.pyc", line 54, in isabs
AttributeError: 'list' object has no attribute 'startswith'

**Comment by weiweihuanghuang** [comment]
Oops I had double square brackets around the list of fonts.
